### ISSUE TITLE
Issues related to NavigationTabs

### ISSUE THREAD

**Issue by JunWei96** [CS2103-AY1819S1-W12-3/main#158]
Code Style
- [x] `NavigationCommand` to change to `TestCommand`.
- [x] Remove `NavigationCommandParser`. There is no need for this.

Task
- [x] Create `ReviewCommand`.
- [x] Allow `TestCommand`, `ReviewCommand` to switch to their respective tabs. `LearnCommand` can switch to learnTab in #160 

Bugs
- [x] Ensure that appstate is updated each time the tabs are switched. So that user would not be executing commands that are meant for other pages. https://stackoverflow.com/questions/17522686/javafx-tabpane-how-to-listen-to-selection-changes [Guide on how listen for tab changes]
- [x] Contents of tabPane gets covered by tabPane after content is updated. [Current workaround is to use original TabPane instead of JFXTabPane in #161 ] -JW

Documentation 
- [x] Update UserGuide to be more `page` oriented. Allowing user to know at what page, the user can execute what command.

**Comment by shaniceabigail** [comment]
Hi JunWei, 

I managed to fix some of the issues, but can you explain the bug:

_Ensure that appstate is updated each time the tabs are switched. So that user would not be executing commands that are meant for other pages. https://stackoverflow.com/questions/17522686/javafx-tabpane-how-to-listen-to-selection-changes [Guide on how listen for tab changes]"_

I'll work on the documentation in the meantime. I'll PR for the current updates, thanks for the heads-up and how to fix the issues!

**Comment by JunWei96** [comment]
> Hi JunWei,
> 
> I managed to fix some of the issues, but can you explain the bug:
> 
> _Ensure that appstate is updated each time the tabs are switched. So that user would not be executing commands that are meant for other pages. https://stackoverflow.com/questions/17522686/javafx-tabpane-how-to-listen-to-selection-changes [Guide on how listen for tab changes]"_
> 
> I'll work on the documentation in the meantime. I'll PR for the current updates, thanks for the heads-up and how to fix the issues!

Steps to reproduce:
1. You can try switching to testPane by clicking. 
2. Then try add card using AddCommand. 
3. The app currently allows you to add card and other stuff (e.g. edit) because its AppState is not updated when the UI changes. Hence, you would need to update the AppState when tabs are switched by clicking.

**Comment by JunWei96** [comment]
I realised your PR #163 does not update the appState when the `TestCommand`, `ReviewCommand` is execute. Do update the AppState over there too. You can look at `LearnCommand`, on how to update the AppState.
