### ISSUE TITLE
Add About us Page

### ISSUE THREAD

**Issue by JunWei96** [CS2103-AY1819S1-W12-3/main#3]
Ref: https://nus-cs2103-ay1819s1.github.io/cs2103-website/admin/project-w06-mid-v11.html

**Comment by JunWei96** [comment]
Ref: https://nus-cs2103-ay1819s1.github.io/cs2103-website/admin/project-w06-mid-v11.html

**Comment by hozongsien** [comment]
I created a new branch with the relavant changes, please do take a look thanks
