### ISSUE TITLE
Port over addressbook features to trivia

### ISSUE THREAD

**Issue by JunWei96** [CS2103-AY1819S1-W12-3/main#6]
1. [x] add
2. [x] edit
3. [x] find
4. [x] list
5. [x] select
6. [ ] clear
7. [x] delete
8. [x] exit
9. [x] help
10. [x] history
11. [x] undo
12. [x] redo

**Comment by hozongsien** [comment]
I have created a PR for the ported list and select command, please do take a look.

**Comment by hozongsien** [comment]
![image](https://user-images.githubusercontent.com/42339979/45673758-21038980-bb5e-11e8-9b93-c25d88165aa2.png)

**Comment by JunWei96** [comment]
`clear` command will be removed.
